version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./src:/var/www/html
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        build: .
        volumes:
            - ./src:/var/www/html
        networks:
            - code-network
#        links:    
#            - mysql

#    mysql:
#        image: mysql:latest
#        ports:
#            - "3306:3306"
#        volumes:
#            - ./mysql:/var/lib/mysql
#        environment:
#            MYSQL_ROOT_PASSWORD: "root"
#            MYSQL_DATABASE: "main"
#        networks:
#            - code-network

networks:
    code-network:
        driver: bridge
